apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: global
  namespace: argocd
  finalizers: [resources-finalizer.argocd.argoproj.io]
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: global
  sources:
    - repoURL: https://github.com/mwdomino/canary-app.git
      targetRevision: main
      path: charts/global-controller
      helm:
        valueFiles:
          - $values/apps/global/values.yaml
    - repoURL: https://github.com/mwdomino/k8s-canary.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: argoproj.io
      kind: Rollout
      jsonPointers:
        - /spec/replicas
