apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: location-stage
  namespace: argocd
  finalizers: [resources-finalizer.argocd.argoproj.io]
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: stage
  sources:
    - repoURL: https://github.com/mwdomino/canary-app.git
      targetRevision: main
      path: charts/location-apps
      helm:
        valueFiles:
          - $values/apps/location/stage/values.yaml
    - repoURL: https://github.com/mwdomino/k8s-canary.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
